Style/StringLiterals:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Lint/ShadowedArgument:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false